apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-04-29T22:17:37Z"
  name: bob
  namespace: default
  resourceVersion: "9308"
  uid: f6dffefe-aef8-4bb7-a62a-75aade058945
secrets:
- name: bob-token-kjsdl