apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-admin

subjects:
- kind: User
  name: "bob"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io