apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    tier: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: paymentservice
  template:
    metadata:
      labels:
        tier: paymentservice
        app: paymentservice
    spec:
      containers:
      - name: server
        image: evheny/public:otus-paymentservice.v0.0.1
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]  
            
