apiVersion: v1 # Версия API

kind: Pod # Объект, который создаем

metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    app: web

spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: nginx-otus #Название контейнера
    image: evheny/public:otus-nginx-docker  # Образ из которого создается контейнер
